name: Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get -y install cmake
    - name: Build and Run Tests
      run: |
        cmake -S . -B build
        cmake --build build
        cd build
        ctest --output-on-failure
